### ISSUE TITLE
Avoid inconsistencies by not caching accountHex 

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-core-ethereum#2]
https://github.com/hoprnet/hopr-core-ethereum/blob/4ad901e058e341579779c3a259a3baa80594ca82/src/index.ts#L118

Avoid saving multpile representations of one variable. String conversion is indeed not the fastest operation, but having (possible) inconsistencies is worse

**Comment by robertkiel** [comment]
The constructor value `account` is in my opinion also unnecessary because it is derived from the keypair

**Comment by nionis** [comment]
perhaps we add some memoization to this, for now I will remove this occurrence and similar stuff in other files
