### ISSUE TITLE
Check ethereum connector tests

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-core-ethereum#41]
Web3.js sometimes seems to throw Errors like these

```
Error: Maximum number of reconnect attempts reached!
```

Please checkout whether we could handle that error earlier and throw a more meaningful error.

**Comment by nionis** [comment]
@robertkiel does this happen when running tests or when running `hopr-core`?

**Comment by 0xjjpa** [comment]
Seems to be a normal behaviour when all tests pass. Closing for now.
