### ISSUE TITLE
Store tickets & remove tickets

### ISSUE THREAD

**Issue by robertkiel** [hoprnet/hopr-core-ethereum#44]
Once ticket is created

- [ ] Store ticket

Once the ticket has been redeemed it should disappear from the database.

- [ ] Check whether `redeem()` was successful
- [ ] Move ticket from `ticket` to `redeemedTickets` in the database
- [ ] Cleanup unredeemed tickets after x hours / days

**Comment by nionis** [comment]
@robertkiel I think we should cleanup DB only if ticket is no longer valid (counter / hashedSecret) changed.

**Comment by nionis** [comment]
No longer relevant.
