### ISSUE TITLE
Expose hopr-ethereum address to remove it as a dependency

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core-ethereum#84]
- [ ] Move `hopr-ethereum` from `dependency` to `devDepedency`
- [ ] Modify `yarn build` process to expose abi of `channel` and `token` contracts.
- [ ] Modify `package.js`on to include exposed contracts.
- [ ] Updated dependencies to use new package during tests

**Comment by nionis** [comment]
Upcoming `core-ethereum` refactor will address this.
