### ISSUE TITLE
Modify the existing deployment workflow to allow deployment on the xDai Chain upon merge to master

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core-ethereum#95]
- [ ] Modify migration/process workflow to allow dynamic chains to be given on a specific chain.

**Comment by nionis** [comment]
@jjperezaguinaga I am thinking of something like this:

version: 1.0.0-rinkeby, 1.0.0-xdai

workflow checks what network it is by looking at the tag and migrates accordingly

**Comment by 0xjjpa** [comment]
Yeah. Another option would be on going for pushing a branch called `release/$network` so we know which network we are doing, but I'm happy either way.

**Comment by nionis** [comment]
No longer relevant.
