### ISSUE TITLE
Create a method to allow withdrawing xDAI and/or xHOPR tokens from HOPR node to a separate Ethereum address

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core-ethereum#97]
- [x] Update core-connector to allow `withdraw` interface which calls `send|sendToken` as a node to send `xDAI|xHOPR` to any Ethereum address.
- [x] Publish a new package with the updated interface
- [x] Update packages (e.g.`hopr-core`) with new connector interface to allow be called by other interfaces.

**Comment by nionis** [comment]
Fixed in #99
